# Ejercicio accidentes de bicicleta en madrid

Limpieza y manejo de datos en Pandas  
Ejercicio del Master de Data Science de KSchool (19 ed.)

In [2]:
import pandas as pd

Primero, cargar todo el excel sin limpiar

In [3]:
full_xls = pd.ExcelFile("./Accidentes_sucio.xls")

In [4]:
type(full_xls)

pandas.io.excel._base.ExcelFile

Sacar los nombres de las hojas (que corresponden a cada año)

In [5]:
by_sheet_names = full_xls.sheet_names
by_sheet_names

['2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016']

**OJO:** el año 2013 tiene menos lineas (4) por arriba que ignorar (el resto tienen 7)

Pruebo ahora a cargar una hoja, solo con la información necesaria, y añadirle la columna de año

In [10]:
by_year = pd.read_excel("./Accidentes_sucio.xls",
                        sheet_name= by_sheet_names[1],
                        skiprows=blank_rows,
                        index_col=0,
                        usecols="A:K",
                        skipfooter=1)
by_year["AÑO"] = by_sheet_names[1]

In [11]:
by_year

,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,AÑO
DISTRITO_ACCIDENTE,,,,,,,,,,,
ARGANZUELA,403,48,103,75,7,26,15.0,2.0,5.0,6.0,2010
BARAJAS,62,5,34,22,1,11,NaN,NaN,NaN,NaN,2010
CARABANCHEL,357,35,133,114,7,22,14.0,6.0,7.0,1.0,2010
CENTRO,546,43,142,169,2,60,14.0,9.0,13.0,9.0,2010
CHAMARTIN,460,67,128,85,11,77,16.0,1.0,8.0,5.0,2010
CHAMBERI,361,34,86,103,1,66,14.0,5.0,2.0,4.0,2010
CIUDAD LINEAL,404,79,120,90,8,39,12.0,6.0,7.0,2.0,2010
FUENCARRAL-EL PARDO,294,49,165,72,10,26,9.0,6.0,3.0,2.0,2010
HORTALEZA,183,15,68,44,4,11,8.0,4.0,3.0,3.0,2010
LATINA,273,37,93,94,6,24,4.0,7.0,10.0,4.0,2010
MONCLOA-ARAVACA,350,47,177,75,10,45,9.0,6.0,9.0,11.0,2010
MORATALAZ,127,21,58,33,6,13,5.0,2.0,2.0,1.0,2010
PUENTE DE VALLECAS,324,44,157,107,7,20,9.0,3.0,8.0,7.0,2010
RETIRO,349,55,33,57,2,45,12.0,7.0,7.0,5.0,2010
SALAMANCA,506,44,131,89,6,89,19.0,1.0,9.0,6.0,2010
SAN BLAS,274,27,62,66,2,22,6.0,2.0,5.0,2.0,2010
TETUAN,331,25,87,89,3,47,13.0,6.0,4.0,3.0,2010
USERA,178,36,78,78,4,14,2.0,4.0,NaN,4.0,2010
VICALVARO,65,4,60,22,3,16,NaN,1.0,1.0,5.0,2010
VILLA DE VALLECAS,124,9,63,32,8,9,3.0,1.0,NaN,3.0,2010
VILLAVERDE,147,21,58,54,2,9,4.0,2.0,2.0,1.0,2010

In [12]:
#Compruebo que efectivamente es un DataFrame
type(by_year)

pandas.core.frame.DataFrame

**Juntar todas las hojas en un solo excel**  

Primero, creo un DataFrame cargando la primera hoja  

Después, uso un *for loop* para ir cargando cada hoja una a una, a un objeto independiente,  
y lo combino con el DataFrame inicial  

Uso un *if* para cargar de forma diferente la del año 2013 del resto (por el numero de filas a omitir)

In [6]:
full_excel = pd.read_excel("./Accidentes_sucio.xls",
                        sheet_name= by_sheet_names[0],
                        skiprows=7,
                        index_col=0,
                        usecols="A:K",
                        skipfooter=1)
full_excel["AÑO"] = by_sheet_names[0]

for i in range(1,len(by_sheet_names)):
    if by_sheet_names[i] == '2013' :
        by_year = pd.read_excel("./Accidentes_sucio.xls",
                        sheet_name= by_sheet_names[i],
                        skiprows=4,
                        index_col=0,
                        usecols="A:K",
                        skipfooter=1)
        by_year["AÑO"] = by_sheet_names[i]
        
    else:
        by_year = pd.read_excel("./Accidentes_sucio.xls",
                        sheet_name= by_sheet_names[i],
                        skiprows=7,
                        index_col=0,
                        usecols="A:K",
                        skipfooter=1)
        by_year["AÑO"] = by_sheet_names[i]
    full_excel = pd.concat([full_excel, by_year], axis=0, sort=False)
        
full_excel

,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,AÑO
DISTRITO_ACCIDENTE,,,,,,,,,,,
ARGANZUELA,389,54,126,75,9.0,43,9.0,4.0,5.0,8.0,2009
BARAJAS,89,6,53,21,NaN,12,2.0,1.0,2.0,2.0,2009
CARABANCHEL,375,44,171,137,8.0,36,13.0,6.0,9.0,8.0,2009
CENTRO,514,55,171,143,NaN,61,12.0,3.0,10.0,12.0,2009
CHAMARTIN,494,70,133,92,10.0,72,22.0,2.0,6.0,7.0,2009
...,...,...,...,...,...,...,...,...,...,...,...
TETUAN,330,43,70,91,NaN,73,25.0,13.0,5.0,3.0,2016
USERA,206,27,74,75,2.0,16,2.0,5.0,4.0,1.0,2016
VICALVARO,70,4,38,22,4.0,15,2.0,3.0,2.0,1.0,2016
VILLA DE VALLECAS,149,7,42,54,5.0,26,4.0,4.0,1.0,3.0,2016
VILLAVERDE,177,11,71,54,1.0,8,5.0,6.0,2.0,1.0,2016

In [19]:
colnames = pd.Series(full_excel.columns)
colnames

0     COLISIÓN DOBLE
1     COLISIÓN MÚLTIPLE
2     CHOQUE CON OBJETO FIJO
3     ATROPELLO
4     VUELCO
5     CAÍDA MOTOCICLETA
6     CAÍDA CICLOMOTOR
7     CAÍDA BICICLETA
8     CAÍDA VIAJERO BUS
9     OTRAS CAUSAS
10                                         AÑO
dtype: object

Las columnas necesitan nombres mejores (tienen muchos espacios, tildes...)

Primera prueba sustituyendo

In [10]:
colnames.str.replace('  ', '').str.replace(' ', '_')

0             COLISIÓN_DOBLE
1         COLISIÓN_MÚLTIPLE_
2     CHOQUE_CON_OBJETO_FIJO
3                 ATROPELLO_
4                     VUELCO
5         CAÍDA_MOTOCICLETA_
6           CAÍDA_CICLOMOTOR
7           CAÍDA_BICICLETA_
8         CAÍDA_VIAJERO_BUS_
9               OTRAS_CAUSAS
10                       AÑO
dtype: object

Funciona, pero aún hay que eliminar algunos al final y quitar las tildes

Ahora, modificando el objeto (Series) con el listado de nombres

In [20]:
colnames = colnames.str.replace('  ', '').str.replace(' ', '_').str.replace('Ó', 'O').str.replace('Í', 'I').str.replace('Ú', 'U')
colnames = colnames.apply(lambda x: x[:-1]+x[-1:].replace('_', ''))
colnames

0             COLISION_DOBLE
1          COLISION_MULTIPLE
2     CHOQUE_CON_OBJETO_FIJO
3                  ATROPELLO
4                     VUELCO
5          CAIDA_MOTOCICLETA
6           CAIDA_CICLOMOTOR
7            CAIDA_BICICLETA
8          CAIDA_VIAJERO_BUS
9               OTRAS_CAUSAS
10                       AÑO
dtype: object

Ahora si, lo meto como nuevos nombres

In [22]:
full_excel.columns = colnames
full_excel.head(2)

,COLISION_DOBLE,COLISION_MULTIPLE,CHOQUE_CON_OBJETO_FIJO,ATROPELLO,VUELCO,CAIDA_MOTOCICLETA,CAIDA_CICLOMOTOR,CAIDA_BICICLETA,CAIDA_VIAJERO_BUS,OTRAS_CAUSAS,AÑO
DISTRITO_ACCIDENTE,,,,,,,,,,,
ARGANZUELA,389,54,126,75,9.0,43,9.0,4.0,5.0,8.0,2009
BARAJAS,89,6,53,21,NaN,12,2.0,1.0,2.0,2.0,2009

Guardar la tabla con todos los años como un unico csv

In [23]:
full_excel.to_csv("./Accidentes_limpio.csv")